"""Add transaction_status to properties

Revision ID: 08ac26af9353
Revises: 19c2ac6eb7ef
Create Date: 2025-09-24 11:22:46.747849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ac26af9353'
down_revision: Union[str, None] = '19c2ac6eb7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    transaction_status_enum = sa.Enum('S', 'L', 'SL', 'JV', name='transactionstatus')
    transaction_status_enum.create(op.get_bind())
    
    # Add the transaction_status column with default value for existing records
    op.add_column('properties', sa.Column('transaction_status', transaction_status_enum, nullable=False, server_default='S'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'transaction_status')
    # Drop the enum type
    sa.Enum(name='transactionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
