"""Add middle_name to user table

Revision ID: 19c2ac6eb7ef
Revises: draft_nego_table_001
Create Date: 2025-09-24 10:11:52.363222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c2ac6eb7ef'
down_revision: Union[str, None] = 'draft_nego_table_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_draft_nego_tables_id', table_name='draft_nego_tables')
    op.drop_table('draft_nego_tables')
    op.add_column('user', sa.Column('middle_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middle_name')
    op.create_table('draft_nego_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('form_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('negotiations_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('financial_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('step_completed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_auto_save', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='draft_nego_tables_property_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='draft_nego_tables_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='draft_nego_tables_pkey')
    )
    op.create_index('ix_draft_nego_tables_id', 'draft_nego_tables', ['id'], unique=False)
    # ### end Alembic commands ###
