"""Add Address table and relationship to Property

Revision ID: 426b39e14954
Revises: deb5a8165c13
Create Date: 2025-09-30 11:33:57.477465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426b39e14954'
down_revision: Union[str, None] = 'deb5a8165c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=True),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('place_types', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_components', 'addresses', ['city', 'province', 'postal_code'], unique=False)
    op.create_index('idx_admin_divisions', 'addresses', ['region', 'province', 'city', 'barangay'], unique=False)
    op.create_index('idx_coordinates', 'addresses', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_addresses_barangay'), 'addresses', ['barangay'], unique=False)
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_latitude'), 'addresses', ['latitude'], unique=False)
    op.create_index(op.f('ix_addresses_longitude'), 'addresses', ['longitude'], unique=False)
    op.create_index(op.f('ix_addresses_place_id'), 'addresses', ['place_id'], unique=True)
    op.create_index(op.f('ix_addresses_postal_code'), 'addresses', ['postal_code'], unique=False)
    op.create_index(op.f('ix_addresses_province'), 'addresses', ['province'], unique=False)
    op.create_index(op.f('ix_addresses_region'), 'addresses', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_region'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_province'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_postal_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_place_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_longitude'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_latitude'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_barangay'), table_name='addresses')
    op.drop_index('idx_coordinates', table_name='addresses')
    op.drop_index('idx_admin_divisions', table_name='addresses')
    op.drop_index('idx_address_components', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
