"""add_missing_property_types

Revision ID: 4f232846b0a8
Revises: 426b39e14954
Create Date: 2025-09-30 14:45:01.999083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f232846b0a8'
down_revision: Union[str, None] = '426b39e14954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing PropertyType enum values
    op.execute("ALTER TYPE propertytype ADD VALUE IF NOT EXISTS 'LAND_ONLY'")
    op.execute("ALTER TYPE propertytype ADD VALUE IF NOT EXISTS 'LAND_AND_BUILDING'")
    op.execute("ALTER TYPE propertytype ADD VALUE IF NOT EXISTS 'BUILDING_ONLY'")
    op.execute("ALTER TYPE propertytype ADD VALUE IF NOT EXISTS 'HOTEL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
