"""Add Google Places API fields to properties

Revision ID: 5af7d74d6c83
Revises: f41df5d9d8a2
Create Date: 2025-09-30 11:14:05.664396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af7d74d6c83'
down_revision: Union[str, None] = 'f41df5d9d8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('place_id', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('province_name', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'country')
    op.drop_column('properties', 'province_name')
    op.drop_column('properties', 'place_id')
    # ### end Alembic commands ###
