"""Add draft nego table

Revision ID: draft_nego_table_001
Revises: cb38ae4a1822
Create Date: 2024-12-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'draft_nego_table_001'
down_revision = 'cb38ae4a1822'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_nego_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('negotiations_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('step_completed', sa.String(length=50), nullable=True),
    sa.Column('last_auto_save', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_nego_tables_id'), 'draft_nego_tables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_nego_tables_id'), table_name='draft_nego_tables')
    op.drop_table('draft_nego_tables')
    # ### end Alembic commands ###