"""Add nego table and negotiation entry models

Revision ID: cb38ae4a1822
Revises: 
Create Date: 2025-09-19 10:09:06.794928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb38ae4a1822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nego_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('referred_date', sa.DateTime(), nullable=False),
    sa.Column('source_origin', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_position', sa.String(length=255), nullable=True),
    sa.Column('original_property_name', sa.String(length=255), nullable=False),
    sa.Column('current_property_name', sa.String(length=255), nullable=False),
    sa.Column('original_owner', sa.String(length=255), nullable=True),
    sa.Column('current_owner', sa.String(length=255), nullable=True),
    sa.Column('original_location', sa.Text(), nullable=False),
    sa.Column('current_location', sa.Text(), nullable=False),
    sa.Column('original_property_type', sa.String(length=255), nullable=False),
    sa.Column('current_property_type', sa.String(length=255), nullable=False),
    sa.Column('original_lot_area', sa.Float(), nullable=False),
    sa.Column('current_lot_area', sa.Float(), nullable=False),
    sa.Column('original_cfa', sa.Float(), nullable=True),
    sa.Column('current_cfa', sa.Float(), nullable=True),
    sa.Column('original_frontage', sa.Float(), nullable=True),
    sa.Column('current_frontage', sa.Float(), nullable=True),
    sa.Column('original_depth', sa.Float(), nullable=True),
    sa.Column('current_depth', sa.Float(), nullable=True),
    sa.Column('original_nor', sa.Integer(), nullable=True),
    sa.Column('current_nor', sa.Integer(), nullable=True),
    sa.Column('original_parking', sa.String(length=255), nullable=True),
    sa.Column('current_parking', sa.String(length=255), nullable=True),
    sa.Column('original_zonal_value', sa.String(length=255), nullable=True),
    sa.Column('current_zonal_value', sa.String(length=255), nullable=True),
    sa.Column('original_orientation', sa.String(length=255), nullable=True),
    sa.Column('current_orientation', sa.String(length=255), nullable=True),
    sa.Column('original_lot_shape', sa.String(length=255), nullable=True),
    sa.Column('current_lot_shape', sa.String(length=255), nullable=True),
    sa.Column('sale_total', sa.Float(), nullable=True),
    sa.Column('sale_per_sqm', sa.Float(), nullable=True),
    sa.Column('lease_rate', sa.Float(), nullable=True),
    sa.Column('monthly_lease', sa.Float(), nullable=True),
    sa.Column('intended_rooms', sa.Integer(), nullable=True),
    sa.Column('investment', sa.Float(), nullable=True),
    sa.Column('pby_roi_operations', sa.Float(), nullable=True),
    sa.Column('pby_roi_properties', sa.Float(), nullable=True),
    sa.Column('pby_roi_combined', sa.Float(), nullable=True),
    sa.Column('name_in_tct', sa.String(length=255), nullable=True),
    sa.Column('living_status', sa.String(length=100), nullable=True),
    sa.Column('residency_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='negotablestatus'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nego_tables_id'), 'nego_tables', ['id'], unique=False)
    op.create_table('negotiation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nego_table_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('owner_representative', sa.String(length=255), nullable=False),
    sa.Column('subject_matter', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('mode_of_transaction', sa.Enum('PHONE', 'EMAIL', 'FACE_TO_FACE', 'VIDEO_CALL', 'LETTER', name='transactionmode'), nullable=True),
    sa.Column('floor_area', sa.Float(), nullable=True),
    sa.Column('rental_per_month', sa.Float(), nullable=True),
    sa.Column('rental_per_sqm', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_price_per_sqm', sa.Float(), nullable=True),
    sa.Column('lease_term', sa.Integer(), nullable=True),
    sa.Column('escalation', sa.Float(), nullable=True),
    sa.Column('escalation_start_year', sa.Integer(), nullable=True),
    sa.Column('rent_free_period', sa.Integer(), nullable=True),
    sa.Column('advance_rent', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Integer(), nullable=True),
    sa.Column('other_concerns', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nego_table_id'], ['nego_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_entries_id'), 'negotiation_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_entries_id'), table_name='negotiation_entries')
    op.drop_table('negotiation_entries')
    op.drop_index(op.f('ix_nego_tables_id'), table_name='nego_tables')
    op.drop_table('nego_tables')
    # ### end Alembic commands ###
