"""Add structured Address table with Google Places integration

Revision ID: deb5a8165c13
Revises: 5af7d74d6c83
Create Date: 2025-09-30 11:24:59.646591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb5a8165c13'
down_revision: Union[str, None] = '5af7d74d6c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
