"""add_account_status_to_user_table

Revision ID: e38a28be0e92
Revises: 4f232846b0a8
Create Date: 2025-10-01 11:53:16.149895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38a28be0e92'
down_revision: Union[str, None] = '4f232846b0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    account_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='accountstatus')
    account_status_enum.create(op.get_bind())
    
    # Add the column with a default value
    op.add_column('user', sa.Column('account_status', account_status_enum, nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_status')
    # Drop the enum type
    sa.Enum(name='accountstatus').drop(op.get_bind())
    # ### end Alembic commands ###
