"""add_duplicate_tracking_and_notifications

Revision ID: f3950a9ad6f4
Revises: 5a57597ae57a
Create Date: 2025-10-03 12:50:32.065553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3950a9ad6f4'
down_revision: Union[str, None] = '5a57597ae57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('DUPLICATE_DETECTED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'PROPERTY_ASSIGNED', 'PROPERTY_MERGED', 'SYSTEM_ALERT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_property_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('negotiation_chronicle_attachments_nego_table_id_fkey', 'negotiation_chronicle_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'negotiation_chronicle_attachments', 'nego_tables', ['nego_table_id'], ['id'])
    
    # Add is_duplicate column with default value for existing rows
    op.add_column('properties', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    op.execute('UPDATE properties SET is_duplicate = false WHERE is_duplicate IS NULL')
    op.alter_column('properties', 'is_duplicate', nullable=False)
    
    op.add_column('properties', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('duplicate_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'properties', 'properties', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'duplicate_notes')
    op.drop_column('properties', 'duplicate_of_id')
    op.drop_column('properties', 'is_duplicate')
    op.drop_constraint(None, 'negotiation_chronicle_attachments', type_='foreignkey')
    op.create_foreign_key('negotiation_chronicle_attachments_nego_table_id_fkey', 'negotiation_chronicle_attachments', 'nego_tables', ['nego_table_id'], ['id'], ondelete='CASCADE')
    op.drop_table('notifications')
    # ### end Alembic commands ###
