"""Add detailed address columns to properties

Revision ID: f41df5d9d8a2
Revises: 08ac26af9353
Create Date: 2025-09-25 15:44:01.142002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41df5d9d8a2'
down_revision: Union[str, None] = '08ac26af9353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('street', sa.String(length=200), nullable=True))
    op.add_column('properties', sa.Column('barangay_name', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('city_name', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('properties', sa.Column('region_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'region_name')
    op.drop_column('properties', 'zip_code')
    op.drop_column('properties', 'city_name')
    op.drop_column('properties', 'barangay_name')
    op.drop_column('properties', 'street')
    # ### end Alembic commands ###
